dataset:
    type: "miniImagenet"
    base_file: "filelists/miniImagenet/base.json"
    val_file: "filelists/miniImagenet/val.json"
    novel_file: "filelists/miniImagenet/novel.json"
    num_class: 64

train:
    stop_epoch: 400

